# Generated by Django 5.1.15 on 2026-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_notification_read_by_notification_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('inventory', 'Inventory Manager'), ('admin', 'Admin')], max_length=20),
        ),
    ]
